apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo
  name: dso-demo
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'dso-demo'
        vault.hashicorp.com/agent-inject-secret-database: 'secret/dso-demo/database'
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/dso-demo/database" -}}
            mysql -u {{ .Data.data.username }} -p {{ .Data.data.password }} -h database:3306 mydb
          {{- end -}}
      creationTimestamp: null
      labels:
        app: dso-demo
    spec:
      serviceAccountName: dso-demo
      containers:
      - image: salimhaniff/dso-demo
        name: dso-demo
        ports:
        - containerPort: 8080
        securityContext:
          capabilities:
            drop:
              - ALL
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 11000
          readOnlyRootFilesystem: true
        resources: 
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        volumeMounts:
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}

status: {}
